# sim_structured_long_term config

# Information about range-finder data
scan_num: 15 # How many scans to use
max_range: 8 # Sensor max range (m)

# Bounds on map height
min_z: 0
max_z: 4.3

original_size: true
predict: false
